language: python
python:
  - 2.7

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest

# command to run tests
script:
  - py.test webapp/test/test-all.py
  #- py.test test-all.py
